env: flex
runtime: custom
service: backend

manual_scaling:
  instances: 1

network:
  session_affinity: true

vpc_access_connector:
 name: projects/munio-2/locations/us-central1/connectors/internal-services-connect

handlers:

- url: /.*
  script: auto
  secure: always