services:
  db:
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_USER: webserveruser
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: munio_data
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql
    secrets:
       - db_root_password
       - db_password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 2s
      retries: 20
  
  storage:
    build: 
      context: .
      dockerfile: Dockerfile.storage
    image: fsouza/fake-gcs-server:1
    command: -scheme http
    ports:
      - 4443:4443
    networks:
      - backend
    volumes:
      - storage:/data
    
secrets:
  db_password:
    file: db_password.txt
  db_root_password:
    file: db_root_password.txt

volumes:
    db_data:
    storage:

networks:
  backend:
    driver: bridge